[NZPMC-006] Created database schema / basic graphql files
UoaWDCC/nzpmc_backend pull request #3
Opened 2021-05-02 07:46 UTC by Kingston802

**Issue**

The previous schema was an example one.

**Solution**

Implemented the schema described in CZ's design document: [link](https://docs.google.com/document/d/19tFyLQHdJR7-pJrncysTQysQaJuDGlJADo9HaH7ZQFo/edit#
)

**Risk**

Low risk. 

**Reviewers**

Scorpionknifes
Will

2021-05-02 16:23 UTC, scorpionknifes requested changes
Great Work!

Just a couple of things to do more for this PR!

2021-05-02 16:23 UTC, scorpionknifes commented on index.js
> +// const inputs = readFileSync('./schemas/inputs.graphql').toString('utf-8')
Suggestion:
use `fs.readdirSync` with wildcard `*.graphql` to get an array of `filepaths`
use `filepaths.map(()=>...)` to create a typeDefs

2021-05-02 16:23 UTC, scorpionknifes commented on schemas/mutations.graphql
> +
Implement your first mutation example: 
- `createQuestion(form: CreateQuestion): Question` with `Input CreateQuestion` in `input.graphql` file

2021-05-02 16:23 UTC, scorpionknifes commented on schemas/objects.graphql
> +    id: ID!
Let's define all the variables from the database schema.

also, define a nested query e.g

```gql
type Quiz {
	...
	questions: [Question]
	...
}
```

some of the nested query you can implement:
- Quiz -> Question
- Question -> Options
- UserQuiz -> Quiz, User (remember to remove UserAnswer)
- UserQuiz -> UserQuizAnswer

2021-05-02 16:23 UTC, scorpionknifes commented on schemas/objects.graphql
> +    id: ID!
We can also do queries inside types e.g
```gql
type Quiz {
	...
	questions: [Question]
	"Get question by index"
	question(index: Int!): Question 
	...
}
```

2021-05-02 16:23 UTC, scorpionknifes commented on schemas/schema.graphql
> +    userQuizAnswers(quizID: ID!): [UserQuizAnswer]
Let's add another query - `userQuizzes: [UserQuiz]`
And change - `userQuiz(quizID: ID!): UserQuiz`
Remove `userQuizAnswers`

This is cause we are adding UserQuizAnswer inside

2021-05-09 10:04 UTC, Kingston802 commented
Completed most changes but need to discuss nested queries and objects (UserAnswer vs UserQuizAnswer) with CZ.

2021-05-10 02:36 UTC, scorpionknifes approved these changes
LGTM

2021-05-10 03:22 UTC, Will-ZYS approved these changes
LGTM

2021-05-10 03:24 UTC, merged